---
title: "Tutorials"
date: "Last updated: `r Sys.time()`"
output: 
  html_document: 
    theme: lumen
---


The following links will help get you started with the initial set-up for some 
data science-related programs. 



```{r, echo=FALSE}
# Get list of folders in current directory
tuts <- dir(pattern = "^[^.]+$")

# Get number of folders
my_length <- length(tuts)

# Initiate vector for loop
children <- vector("character", length = my_length)

# Get full path to each .Rmd file and store in 'children'
for (i in 1:my_length) {
  
  # List .Rmd files in each folder of 'folders'
  # store output in 'children'
  children[i] <- list.files(path = tuts[i], 
                            pattern = ".html", 
                            full.names = TRUE)
}

```

```{r, results='asis', echo=FALSE}
# Use directory names for link reference
link_names <- paste0('[', tuts, ']')

# Set base URL
url_root <- "http://www.jvcasillas.com/"

# Set class-specigic url
url_class <- "ru_teaching/ru_spanish_589/589_01_s2018/sources/tuts/"

# Set tutorial-specific url ending
url_ending <- substr(children, 
                     start = 1, 
                     stop = max(nchar(children)))

# Combine everything into a markdown link
url <- paste0(link_names, '(', url_root, url_class, url_ending, ')')

# Combine everything into an unordered list
cat(paste('-', url, '\n'))
```

